server.port=8081
server.address=0.0.0.0

# Explicitly tell Spring to use the MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Use the full URL from TiDB
spring.datasource.url=jdbc:mysql://${TIDB_HOST}:${TIDB_PORT}/studify?createDatabaseIfNotExist=true&useSSL=true&enabledTLSProtocols=TLSv1.2,TLSv1.3
spring.datasource.username=${TIDB_USER}
spring.datasource.password=${TIDB_PASSWORD}

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect