export const mockStudents = [
  {
    id: "1",
    name: "Aarav Sharma",
    email: "aarav.sharma@college.com",
    rollNumber: "CSE2025001",
    department: "cse",
    division: "A",
    phone: "+919876543210",
    dateOfBirth: "2004-02-15",
    gender: "Male",
    address: "123 Tech Park Rd, Pune",
    guardianName: "Rajesh Sharma",
    guardianPhone: "+919812345678",
    enrollmentDate: "2025-08-01",
    status: "active",
  },
  {
    id: "2",
    name: "Priya Verma",
    email: "priya.verma@college.com",
    rollNumber: "IT2025002",
    department: "it",
    division: "A",
    phone: "+919812345679",
    dateOfBirth: "2004-06-22",
    gender: "Female",
    address: "45 Green Valley, Mumbai",
    guardianName: "Anil Verma",
    guardianPhone: "+919876543211",
    enrollmentDate: "2025-08-01",
    status: "active",
  },
  {
    id: "3",
    name: "Rohan Mehta",
    email: "rohan.mehta@college.com",
    rollNumber: "ECE2025003",
    department: "ece",
    division: "B",
    phone: "+919812345680",
    dateOfBirth: "2003-11-10",
    gender: "Male",
    address: "78 Hill Street, Bengaluru",
    guardianName: "Sunita Mehta",
    guardianPhone: "+919812345681",
    enrollmentDate: "2025-08-01",
    status: "active",
  },
  {
    id: "4",
    name: "Isha Nair",
    email: "isha.nair@college.com",
    rollNumber: "MECH2025004",
    department: "mech",
    division: "C",
    phone: "+919812345682",
    dateOfBirth: "2004-01-25",
    gender: "Female",
    address: "92 Lotus Lane, Chennai",
    guardianName: "Ravi Nair",
    guardianPhone: "+919812345683",
    enrollmentDate: "2025-08-01",
    status: "active",
  },
  {
    id: "5",
    name: "Aditya Patel",
    email: "aditya.patel@college.com",
    rollNumber: "CIVIL2025005",
    department: "civil",
    division: "D",
    phone: "+919812345684",
    dateOfBirth: "2003-12-12",
    gender: "Male",
    address: "56 River View, Ahmedabad",
    guardianName: "Manoj Patel",
    guardianPhone: "+919812345685",
    enrollmentDate: "2025-08-01",
    status: "active",
  },
];

export const mockUsers = [
  {
    id: "1",
    name: "Admin User",
    email: "admin@college.com",
    password: "admin123",
    role: "admin",
  },
  {
    id: "2",
    name: "John Doe",
    email: "john@college.com",
    password: "password123",
    role: "admin",
  },
];

export const departments = [
  { value: "CSE", label: "Computer Science Engineering" },
  { value: "IT", label: "Information Technology" },
  { value: "ECE", label: "Electronics and Communication Engineering" },
  { value: "EEE", label: "Electrical and Electronics Engineering" },
  { value: "MECH.", label: "Mechanical Engineering" },
  { value: "CIVIL", label: "Civil Engineering" },
  { value: "AERO.", label: "Aeronautical Engineering" },
  { value: "AUTO", label: "Automobile Engineering" },
];

export const divisions = [
  { value: "A", label: "Division A" },
  { value: "B", label: "Division B" },
  { value: "C", label: "Division C" },
  { value: "D", label: "Division D" },
];
